### ISSUE TITLE
minor fixes 

### ISSUE THREAD

**Issue by selul** [Codeinwp/laravel-uptime-monitor#7]
@preda-bogdan we will need some minor fixes: 

- [x] If the monitor already exists but it has the confirmation email in pending, **no** longer send the confirmation email. Now if I create again the monitor for a website that is already present but not confirmed I get from the API ->
 ```{"status":500,"message":"Could not save a monitor for url `https:\/\/themeisle.com` because there already exists another monitor with the same url. Try saving a monitor with a different url."}```
but the email is still **sending**.
- [x] Instead of http://prntscr.com/ikzcx8 on confirm, please output just the string -> 'https://themeisle.com activated, email confirmed!', not the JSON output. Make sure the url is decoded. -
- [x] The same thing applies to the message when the token is invalid.

**Comment by preda-bogdan** [comment]
@selul Made the requested changes and updated the server. Let me know if there is anything else I can help.

**Comment by selul** [comment]
works great now. thanks !
